import { ContactForm } from "@/components/contact-form"
import { Card, CardContent } from "@/components/ui/card"
import { Clock, Mail, MapPin, Phone } from "lucide-react"
import { company, fullAddress } from "@/lib/company"
import { LightDecor } from "@/components/light-decor"

export const metadata = { title: "Contact – Facade, Glazing & Roofing Inquiries", alternates: { canonical: "/contact" }, description: "Contact Roop Glass Solutions, Mumbai, for glass facade, structural glazing, ACP and stone cladding, glass railing, partition and roofing inquiries. Call +91 93200 08279, Mon–Sat 9 AM–7 PM." }

export default function ContactPage() {
  return <div className="min-h-screen pt-16"><section className="relative overflow-hidden py-20 px-4 bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50 dark:from-slate-900 dark:via-slate-800 dark:to-slate-900"><LightDecor shards beam /><div className="relative z-10 max-w-4xl mx-auto text-center"><h1 className="text-4xl md:text-5xl font-bold text-slate-900 dark:text-white mb-6">Contact Roop Glass Solutions</h1><p className="text-lg text-slate-600 dark:text-slate-300">For commercial glass, facade, cladding, railing and project inquiries.</p></div></section><section className="py-16 px-4"><div className="max-w-6xl mx-auto grid lg:grid-cols-[0.8fr_1.2fr] gap-8"><div className="space-y-4"><Card><CardContent className="p-6 flex gap-4"><Phone className="text-blue-600" /><div><h2 className="font-semibold">Phone</h2><a className="text-slate-600 hover:text-blue-600" href="tel:+919320008279">+91 9320008279</a></div></CardContent></Card><Card><CardContent className="p-6 flex gap-4"><Mail className="text-blue-600" /><div><h2 className="font-semibold">Email</h2><a className="text-slate-600 hover:text-blue-600" href="mailto:info.roopglass@gmail.com">info.roopglass@gmail.com</a></div></CardContent></Card><Card><CardContent className="p-6 flex gap-4"><MapPin className="text-blue-600 shrink-0" /><div><h2 className="font-semibold">Office</h2><p className="text-slate-600">{fullAddress}</p></div></CardContent></Card><Card><CardContent className="p-6 flex gap-4"><Clock className="text-blue-600 shrink-0" /><div><h2 className="font-semibold">Working hours</h2><p className="text-slate-600">{company.hoursText}</p></div></CardContent></Card></div><Card className="light-gradient-border bg-white/70"><CardContent className="p-6 md:p-8"><h2 className="text-2xl font-bold mb-2">Send an inquiry</h2><p className="text-slate-600 mb-7">Tell us about your commercial project or question.</p><ContactForm /></CardContent></Card></div></section></div>
}
