"use client"
import { useMemo, useState } from "react"
import Link from "next/link"
import type { Category, Service } from "@/lib/content"

export function CatalogBrowser({ categories, services, initialCategory }: { categories: Category[]; services: Service[]; initialCategory?: string }) {
  const [category, setCategory] = useState(initialCategory && categories.some((item) => item.slug === initialCategory) ? initialCategory : "all"); const [term, setTerm] = useState("")
  const visible = useMemo(() => services.filter((service) => (category === "all" || service.categorySlug === category) && `${service.name} ${service.excerpt}`.toLowerCase().includes(term.toLowerCase())), [category, term, services])
  return <><div className="flex flex-col md:flex-row gap-4 justify-between mb-8"><input className="rounded-md border px-4 py-2 bg-white dark:bg-slate-900" value={term} onChange={(event) => setTerm(event.target.value)} placeholder="Search the catalog" /><div className="flex gap-2 flex-wrap">{[{ slug: "all", name: "All" }, ...categories].map((item) => <button key={item.slug} onClick={() => setCategory(item.slug)} className={`px-3 py-2 text-sm rounded-full border ${category === item.slug ? "bg-blue-600 text-white border-blue-600" : "bg-white dark:bg-slate-900"}`}>{item.name}</button>)}</div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{visible.map((service) => <Link href={`/catalog/${service.slug}`} key={service.id} className="group rounded-xl overflow-hidden border bg-white dark:bg-slate-900 hover:shadow-lg transition-shadow"><img src={service.imageUrl || "/placeholder.jpg"} alt={service.name} className="w-full h-48 object-cover" /><div className="p-5"><p className="text-xs font-medium uppercase tracking-wide text-blue-600">{categories.find((item) => item.slug === service.categorySlug)?.name}</p><h2 className="text-xl font-semibold mt-1 group-hover:text-blue-600">{service.name}</h2><p className="text-slate-600 dark:text-slate-300 mt-2 text-sm">{service.excerpt}</p><span className="inline-block mt-4 text-sm font-medium text-blue-600">View details →</span></div></Link>)}</div>{visible.length === 0 && <p className="py-12 text-center text-slate-500">No catalog entries match that search.</p>}</>
}
